---
# tasks file for jenkins_teardown
- name: Check for running EC2 instances to Terminate
  ec2_instance_info:
    region: "{{ aws_region }}"
    profile: "{{ aws_root }}"
    filters:
      "tag:Name": "{{ tag_value }}"
      instance-state-name: [ "running" ]
  register: existing_ec2

- debug:
    msg: "------------>{{ existing_ec2.instances[0].instance_id }}"


- name: Terminate EC2 Instance
  ec2:
    region: "{{ aws_region }}"
    profile: "{{ aws_root }}"
    state: absent
    instance_id: existing_ec2.instances[0].instance_id
    wait: yes
  when: existing_ec2.instances

